#!/usr/bin/python3

#SI接頭辞変換ツール

#標準入力 echo"数値 旧単 新単"
#標準出力 変換|数値 単位
#Q,R,Y,Z,E,P,T,G,M,k,h,da, ,d,c,m,μ,n,p,f,a,z,y,r,q計24個

import sys


si  = ["Q","R","Y","Z","E","P","T","G","M","k","h","da","d","c","m","μ","n","p","f","a","z","y","r","q"]
sin = [30,27,24,21,18,15,12,9,6,3,2,1,0,-1,-2,-3,-6,-9,-12,-15,-18,-21,-24,-27,-30]
roop = 0

kyu = 0
new = 0
gap = 0

read = sys.stdin.read().strip()
data = read.split()

for sis in si:
    if data[1] == sis:
       kyu = sin[roop]

    if data[2] == sis:
       new = sin[roop]

    roop +=1

gap = kyu - new
end = float(data[0]) * (10 ** gap)

print(end,data[2])
